# NumPy 

O NumPy é o pacote básico da linguagem Python que permite trabalhar com arranjos, vetores e matrizes de N dimensões, de uma forma comparável e com uma sintaxe semelhante ao software proprietário Matlab, e com toda a expressividade da linguagem. Possui diversas funções e operações sofisticadas, incluindo (mas não se limitando a):

* Objeto array para a implementação de arranjos multidimensionais
* Objeto matrix para o cálculo com matrizes
* Ferramentas para Álgebra linear
* Transformadas de Fourier básicas
* Ferramentas sofisticadas para geração de números aleatórios

Além disso tudo, as classes criadas podem ser facilmente herdadas, permitindo a customização do comportamento (por exemplo, dos operadores tópicos de adição, subtração, multiplicação, etc.).

## Instalação no Anaconda

Vá ao terminal ou ao prompt de commando e digite:
    
    conda install numpy
    
**Caso não tenha o Anaconda e não possa instalá-lo, observe as instruções dispostas [aqui.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Utilizando NumPy

Uma vez instalado você pode importá-lo:

In [1]:
import numpy as np

# Numpy Arrays

## Criando NumPy Arrays

### De uma lista

In [2]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [3]:
np.array(minha_lista)

array([1, 2, 3])

In [4]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos internos

Existem muitas maneiras de se criar Arrays.

### arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,1.2)

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8])

### Zeros e uns

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

In [12]:
np.linspace(0,10,34)

array([ 0.        ,  0.3030303 ,  0.60606061,  0.90909091,  1.21212121,
        1.51515152,  1.81818182,  2.12121212,  2.42424242,  2.72727273,
        3.03030303,  3.33333333,  3.63636364,  3.93939394,  4.24242424,
        4.54545455,  4.84848485,  5.15151515,  5.45454545,  5.75757576,
        6.06060606,  6.36363636,  6.66666667,  6.96969697,  7.27272727,
        7.57575758,  7.87878788,  8.18181818,  8.48484848,  8.78787879,
        9.09090909,  9.39393939,  9.6969697 , 10.        ])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## eye

Cria uma matriz identidade

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

### rand
Utiliza a distribuição uniforme.

In [15]:
np.random.rand(20)

array([0.38073936, 0.58026542, 0.64254496, 0.81511625, 0.59324316,
       0.9068744 , 0.10177741, 0.98185786, 0.49066136, 0.40976956,
       0.29785457, 0.61579548, 0.49964872, 0.80903361, 0.38820178,
       0.75532637, 0.67531011, 0.10110544, 0.5686565 , 0.58223092])

In [16]:
np.random.rand(5,5)

array([[0.21137637, 0.30352268, 0.05930889, 0.59207258, 0.05345632],
       [0.31247256, 0.78237021, 0.49462674, 0.26760581, 0.53016131],
       [0.8066178 , 0.85701563, 0.42660767, 0.81764422, 0.77705927],
       [0.61431636, 0.34651806, 0.05583525, 0.46501546, 0.18501461],
       [0.78786891, 0.35060283, 0.90062414, 0.35942812, 0.77519756]])

### randn

Utiliza a distribuição Normal.

In [17]:
np.random.randn(2)

array([0.55958565, 0.89257387])

In [18]:
np.random.randn(5,5)

array([[-0.4246234 ,  0.62419735,  0.66534791,  0.67409824,  1.42351254],
       [ 0.84015192,  1.34798883, -0.46107918,  0.35073158,  0.94423445],
       [-0.74657074,  0.00644852,  0.92701987,  0.26243204, -0.15519936],
       [-0.23209059, -0.29898381,  0.51576157,  0.13881127,  1.30740569],
       [-1.34103276, -0.78907398,  1.09559003,  0.65425305,  0.85298789]])

### randint
Utiliza a distribuição uniforme entre um intervalo, inclusive.

In [19]:
np.random.randint(1,100)

39

In [20]:
np.random.randint(1,100,10)

array([56, 75, 75, 29, 44, 71, 96, 20, 26, 13])

## Reshape
Retorna um array com nova estrutura.

In [21]:
arr = np.random.randint(1,100,25)
arr

array([15, 61, 47, 92,  7, 32, 53, 80,  3, 67, 82, 49, 89, 12, 78, 73, 38,
       70,  2, 49, 17,  1, 28, 70, 62])

In [22]:
arr.reshape(5,5)

array([[15, 61, 47, 92,  7],
       [32, 53, 80,  3, 67],
       [82, 49, 89, 12, 78],
       [73, 38, 70,  2, 49],
       [17,  1, 28, 70, 62]])

### max,min,argmax,argmin

In [23]:
ranarr = arr

In [24]:
arr

array([15, 61, 47, 92,  7, 32, 53, 80,  3, 67, 82, 49, 89, 12, 78, 73, 38,
       70,  2, 49, 17,  1, 28, 70, 62])

In [25]:
ranarr.max()

92

In [26]:
ranarr.argmax()

3

In [27]:
ranarr.min()

1

In [28]:
ranarr.argmin()

21

In [29]:
ranarr.mean()

47.08

## Shape

In [30]:
# Vetor
arr.shape

(25,)

In [31]:
# Note os dois conjuntos de colchetes
arr.reshape(1,25)

array([[15, 61, 47, 92,  7, 32, 53, 80,  3, 67, 82, 49, 89, 12, 78, 73,
        38, 70,  2, 49, 17,  1, 28, 70, 62]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[15],
       [61],
       [47],
       [92],
       [ 7],
       [32],
       [53],
       [80],
       [ 3],
       [67],
       [82],
       [49],
       [89],
       [12],
       [78],
       [73],
       [38],
       [70],
       [ 2],
       [49],
       [17],
       [ 1],
       [28],
       [70],
       [62]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

In [35]:
arr.dtype

dtype('int64')