# Indexação e seleção no NumPy

In [1]:
import numpy as np

In [2]:
# Criando um array simples
arr = np.arange(0,11)

In [3]:
# Apresenta
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Colchetes

In [4]:
arr[0]

0

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Utilizando intervalos de índice.

In [7]:
# Definindo um valor para um intevalo (Broadcasting)
arr[0:5]=100

# Apresenta
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Reseta o array
arr = np.arange(0,11)

# Apresenta
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Fatia
fatia_de_arr = arr[0:6]

# Apresenta fatia
fatia_de_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
# Modifica fatia
fatia_de_arr[:]=99

# Apresenta novamente
fatia_de_arr

array([99, 99, 99, 99, 99, 99])

Observe que as modificações também ocorreram no array original!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Os dados não foram copiados, é uma instância do array original! Isso previne problemas com memória!

In [12]:
# Para obter uma cópia é necessário ser explícito
arr_copia = arr.copy()

arr_copia

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexando um array 2D (matrizes)

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

# Apresenta
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
# Indexando linha
arr_2d[1]


array([20, 25, 30])

In [15]:
# O formato é arr_2d[linha][coluna] ou arr_2d[linha,coluna]

arr_2d[1][0]

20

In [16]:
arr_2d[1,0]

20

In [17]:
# Fatiamento até a linha 2,exclusive, e a partir da segunda coluna 1, inclusive

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
# Linha 2 (última)
arr_2d[2]

array([35, 40, 45])

In [19]:
# Ou
arr_2d[2,:]

array([35, 40, 45])

### "Cercas"

In [20]:
# Definindo uma matriz
arr2d = np.zeros((10,10))

In [21]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
# Comprimento de um array
arr_comprimento = arr2d.shape[1]
arr_comprimento

10

In [23]:
arr2d.shape

(10, 10)

In [24]:
# Definindo um array

for i in range(arr_comprimento):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [25]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [26]:
# Em qualquer ordem
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Mais Indexações

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Seleção

In [27]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr = arr>4

In [30]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[(arr>2) & (arr<9)]

array([3, 4, 5, 6, 7, 8])

In [33]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])